### ISSUE TITLE
NCEP/NCAR Reanalysis

### ISSUE THREAD

**Issue by nickrsan** [climate-mirror/datasets#11]
Name: NCEP/NCAR Reanalysis
Organization: NOAA
Description URL: http://www.esrl.noaa.gov/psd/data/gridded/data.ncep.reanalysis.html
Download URL: ftp://ftp.cdc.noaa.gov/Datasets/ncep.reanalysis/
File Types: 
Size: 
Status: In process as of 2016-12-13

**Comment by teagangosling** [comment]
Starting FTP download now. Once it's locally downloaded I'll get it served up and the URL listed.

**Comment by empirical-bayesian** [comment]
The Azimuth Backup Project also has a completed replica of this site. Is it listed as our Issue #6 at:
https://bitbucket.org/azimuth-backup/azimuth-inventory/issues

It is in final, but there is as of yet no public access to the mirror.

**Comment by teagangosling** [comment]
@empirical-bayesian Oh brilliant! We'll try to make our copy publicly available.

**Comment by mxplusb** [comment]
Awesome! I will go ahead and close out this issue as there is an offline, private mirror.
