### ISSUE TITLE
Dataset at ftp://alt.ngs.noaa.gov/cors/rinex

### ISSUE THREAD

**Issue by nickrsan** [climate-mirror/datasets#138]
Primary server: ftp://geodesy.noaa.gov/cors/rinex
Alternate server: ftp://alt.ngs.noaa.gov/cors/rinex

Global Navigation Satellite System (GNSS)  data collected at these stations are made available to the public by NGS in Receiver INdependent EXchange (RINEX) format.  https://www.ngs.noaa.gov/CORS/

**Comment by stevelord** [comment]
Currently downloading.

**Comment by clickbg** [comment]
Downloading as well.

**Comment by claughinghouse** [comment]
Downloading.

**Comment by patrickegleason** [comment]
Downloading

**Comment by gabefair** [comment]
any success @stevelord , @clickbg , @gleezy ?

**Comment by bkirkbri** [comment]
Looks like @mxplusb is also downloading https://github.com/climate-mirror/datasets/issues/167#issuecomment-275196839

**Comment by donbright** [comment]
i have crashed my machines multiple times trying to get size estimates for big stuff like this.
lftp literally runs out of memory causing itself to get killed.

**Comment by bkirkbri** [comment]
Size for just the `2016` directory is 4.3TB. There are directories from `1994` to `2016` and the older ones appear to be smaller. For example, `1994` is only 218MB.

**Comment by bkirkbri** [comment]
@mxplusb @clickbg @gleezy @stevelord Any luck with this one?

**Comment by mxplusb** [comment]
No, WinSCP failed as well. :/

**Comment by gabefair** [comment]
This data does not need to be backed up. While the cors superset does contain low priority meteorological data, this rinex dataset is not useful to our archive project. 

Thank you everyone for jumping on this. Please consider helping out with other tickets.
