### ISSUE TITLE
Dataset at ftp:/podaac.jpl.nasa.gov/allData/ghrsst

### ISSUE THREAD

**Issue by nickrsan** [climate-mirror/datasets#204]
ftp:/podaac.jpl.nasa.gov/allData/ghrsst.

Suggested in a large email containing many urls

**Comment by gabefair** [comment]
Downloading now

**Comment by bkirkbri** [comment]
Appears to be a duplicate of #192. @gabefair Were you able to mirror this one?

**Comment by bkirkbri** [comment]
Closing as a duplicate of #241. Please comment there instead of here.
