### ISSUE TITLE
Dataset at ftp:/podaac.jpl.nasa.gov/allData/saral

### ISSUE THREAD

**Issue by nickrsan** [climate-mirror/datasets#208]
ftp:/podaac.jpl.nasa.gov/allData/saral.

Suggested in a large email containing many urls

**Comment by wsh** [comment]
Downloading.

**Comment by donbright** [comment]
probable duplicate of #200 and #256

**Comment by wsh** [comment]
Downloaded. Investigating hosting options.

**Comment by bkirkbri** [comment]
@wsh Thanks! Can you post `find podaac.jpl.nasa.gov/allData/saral -type f -exec md5sum {} \; | grep -v \\.listing | md5sum` to help with cross mirror verification?

**Comment by bkirkbri** [comment]
Duplicate of #256

**Comment by wsh** [comment]
```ad38720321c16855fa93c67cd744ca7d```

**Comment by gabefair** [comment]
@wsh , if your copy is still good, can you please comment over at ticket #256, as we will be closing this ticket as its a duplicate.

**Comment by bkirkbri** [comment]
Closing as a duplicate
