### ISSUE TITLE
Dataset at ftp:/podaac.jpl.nasa.gov/pub/sea_surface_height

### ISSUE THREAD

**Issue by nickrsan** [climate-mirror/datasets#213]
ftp://podaac.jpl.nasa.gov/SeaSurfaceTopography/

Suggested in a large email containing many urls

**Comment by wsh** [comment]
This appears to be down.

**Comment by nickrsan** [comment]
Hmm, yeah - this was part of a big URL dump someone sent me, so I'm not sure where they got these. Seems like maybe the data in here could be in ftp://podaac.jpl.nasa.gov/SeaSurfaceTopography/ (as I think you were suggesting in Slack). I'll check if that's included elsewhere and close or modify this as appropriate

**Comment by nickrsan** [comment]
OK, I don't see it elsewhere - I'm going to modify this one to ftp://podaac.jpl.nasa.gov/SeaSurfaceTopography/

**Comment by alex-kazda** [comment]
The subdirectories of ftp://podaac.jpl.nasa.gov/SeaSurfaceTopography/ contains only symlinks to subdirectories of ftp://podaac.jpl.nasa.gov/allData 

Here's what du says:

    lftp podaac.jpl.nasa.gov:/SeaSurfaceTopography> du -d1 -h .
    512     ./aop                                                                    
    47      ./aviso                                                         
    215     ./coastal_alt                                                                 
    22      ./geos3                                                         
    58      ./grace                                                                               
    2.0K    ./jason1                                                                    
    46      ./jason3                                                         
    607     ./merged_alt                                                                 
    46      ./monthly_mean_atlas                                                         
    137     ./ostm                                                         
    65      ./recon_sea_level                                                         
    47      ./saral                                                         
    44      ./tellus                                                         
    447     ./topex                                                                    
    566     ./woce                                                                                 
   4.8K	.

**Comment by bkirkbri** [comment]
> The subdirectories of ftp://podaac.jpl.nasa.gov/SeaSurfaceTopography/ contains only symlinks to subdirectories of ftp://podaac.jpl.nasa.gov/allData

I vote to close.
