### ISSUE TITLE
NASA NESDIS Data

### ISSUE THREAD

**Issue by nickrsan** [climate-mirror/datasets#223]
ftp:/www.star.nesdis.noaa.gov/pub/sod.

Suggested in a large email containing many urls

**Comment by as-com** [comment]
"Connection refused"

**Comment by mxplusb** [comment]
Yeah, same here.

@nickrsan can you ask for a better link from the link provider? thanks.

**Comment by infernix** [comment]
It's ftp://ftp.star.nesdis.noaa.gov/pub/sod/ but the dataset is huge, i stopped counting at 20TB.

**Comment by infernix** [comment]
This is actualy a dupe of #166

**Comment by bkirkbri** [comment]
Closing as a duplicate.
