### ISSUE TITLE
U.S. DOE CDIAC Ocean Carbon Dioxide Data

### ISSUE THREAD

**Issue by nickrsan** [climate-mirror/datasets#225]
http:/cdiac.esd.ornl.gov/ftp/oceans.

Suggested in a large email containing many urls

**Comment by k15z** [comment]
Corresponding FTP link ftp://cdiac.ornl.gov/pub/oceans, downloading now.

**Comment by bkirkbri** [comment]
@k15z Thank you!

Closing as this is a subset of #291 so we have multiple mirrors now.
