### ISSUE TITLE
NASA PODAAC Coastal Sea Surface Height and Currents Data

### ISSUE THREAD

**Issue by nickrsan** [climate-mirror/datasets#240]
ftp:/podaac-ftp.jpl.nasa.gov/allData/coastal_alt.

Suggested in a large email containing many urls

**Comment by Proplex** [comment]
Downloading

**Comment by nubenum** [comment]
Duplicate of #190

**Comment by bkirkbri** [comment]
@Proplex Were you able to complete a mirror of this data? Thanks!

**Comment by donbright** [comment]
agree with @nubenum, this is dup of #190 

Size estimate: 3T

**Comment by gabefair** [comment]
1 vote to close

**Comment by bkirkbri** [comment]
Closing as a duplicate of #190 - comment there with any updates.
