### ISSUE TITLE
NASA PODAAC Salinity Processes in the Upper Ocean Regional Study Data

### ISSUE THREAD

**Issue by nickrsan** [climate-mirror/datasets#244]
ftp:/podaac-ftp.jpl.nasa.gov/allData/insitu.

Suggested in a large email containing many urls

**Comment by adinbied** [comment]
I'll start in on this one!

**Comment by adinbied** [comment]
Alright, got it done and am uploading it to a mirror now.

**Comment by adinbied** [comment]
Dataset Homepage: [ftp://podaac-ftp.jpl.nasa.gov/allData/insitu](ftp://podaac-ftp.jpl.nasa.gov/allData/insitu)
Mirror URLs:  [https://archive.org/details/NASAPODAACSalinityProcessesInTheUpperOceanRegionalStudyData](https://archive.org/details/NASAPODAACSalinityProcessesInTheUpperOceanRegionalStudyData)
Mirrored By: adinbied
Size: 1.61 GB
Responsible Agency: NASA

**Comment by bkirkbri** [comment]
Duplicate of #193.
