### ISSUE TITLE
NASA PODAAC RapidScat Data

### ISSUE THREAD

**Issue by nickrsan** [climate-mirror/datasets#266]
ftp:/podaac.jpl.nasa.gov/allData/rapidscat.

Suggested in a large email containing many urls

**Comment by gabefair** [comment]
Downloading now

**Comment by mxplusb** [comment]
@gabefair is this separate from the Ocean Temperature data?

**Comment by gabefair** [comment]
@mxplusb , I'm not sure about what data it is. But its still downloading. 
I share a dropbox link once I'm done.

**Comment by baobrien** [comment]
Downloading now.

**Comment by baobrien** [comment]
Okay, I've vastly underestimated the size of this dataset. I've used up the 50GB on my public mirror DO droplet and I'm only in 2014. I'll try and re-tool to something based on Backblaze B2 or something tomorrow.

**Comment by gabefair** [comment]
So I also ran out of space, I'm looking into other options as well

**Comment by lgreenlee** [comment]
I can download it, if no one else is working on it.

**Comment by Zanooda** [comment]
3.1 TB in total. Downloading now.

**Comment by gabefair** [comment]
@Zanooda how is it coming?

**Comment by bkirkbri** [comment]
@ivanstegic is also mirroring this one https://github.com/climate-mirror/datasets/issues/207#issuecomment-275873200

**Comment by ivanstegic** [comment]
I'm at 1.1TB, see https://github.com/climate-mirror/datasets/issues/207#issuecomment-276668289

**Comment by bkirkbri** [comment]
Closing in favor of #207
