### ISSUE TITLE
NASA Climate Consensus

### ISSUE THREAD

**Issue by nickrsan** [climate-mirror/datasets#27]
Name: NASA Climate Consensus
Organization: NASA
Description URL: http://climate.nasa.gov/scientific-consensus/
Download URL: 
File Types: 
Size: 
Status: CLAIMED 2016-12-14 Scraping content recursively and completely. Will be made available as offline-viewable content.

**Comment by johncronan** [comment]
#97 is same thing.

**Comment by nickrsan** [comment]
Thanks for flagging John - closing as a duplicate since the other has status updates.
