### ISSUE TITLE
NOAA SSMI-SSMIS Hydrological Products - NCDC Data

### ISSUE THREAD

**Issue by YohannTKuruvila** [climate-mirror/datasets#287]
* *Agency*: NOAA
* *Agency Division*: NCDC
* *Data Type*: Satellite
* *Data Format*: Unknown
* *FTP/HTTP URL*: ftp://eclipse.ncdc.noaa.gov/pub/ssmi/monthly_ncdc/ncdc/

**Comment by blueacid** [comment]
Grabbing

**Comment by blueacid** [comment]
Got; 243MB.

Will mirror soon

**Comment by axlecrusher** [comment]
Cloning

**Comment by axlecrusher** [comment]
Done

**Comment by clickbg** [comment]
Mirrored at http://mirrors.sgate.org/climate-mirror/eclipse.ncdc.noaa.gov/pub/ssmi/monthly_ncdc/ncdc/

**Comment by blueacid** [comment]
Also mirrored at: http://climatedata.project.zone/mirror/eclipse.ncdc.noaa.gov/pub/ssmi/monthly_ncdc/ncdc/

**Comment by wantonwonton** [comment]
I have an offline copy as well.  Here are MD5 checksums for the files ([md5sums.txt](https://github.com/climate-mirror/datasets/files/737747/md5sums.txt)).

**Comment by axlecrusher** [comment]
md5sums match for me

**Comment by bkirkbri** [comment]
Thank you everyone

**Comment by gabefair** [comment]
## 1 vote to close
We have it mirrored twice in this ticket
This is also a subset of #295

**Comment by gabefair** [comment]
Thank you everyone for your help! If you have the bandwidth please consider picking up another dataset for archiving
