### ISSUE TITLE
NOAA ESRL GMD Aerosols

### ISSUE THREAD

**Issue by donbright** [climate-mirror/datasets#302]
* *Agency*:  National Oceanic & Atmospheric Administration (NOAA)
* *Agency Division*: Oceanic and Atmospheric Research (OAR)
* *Agency Subdivision*: Earth System Research Laboratory (ESRL)
* *Agency Sub-Subdivision*: Global Monitoring Division (GMD)
* *Bulk Download Link*: ftp://ftp.cmdl.noaa.gov/data/aer/
* *Size Estimate*: 142G
* *Data Type*: ```"The goals of this regional-scale monitoring program are to characterize means, variability, and trends of climate-forcing properties of different types of aerosols, and to understand the factors that control these properties. GMD's measurements also provide ground-truth for satellite measurements and global models, as well as key aerosol parameters for global-scale models."``` - [GMD Aerosols website](https://www.esrl.noaa.gov/gmd/aero/)

* *Related Issues*: This issue is a split of issue #275

**Comment by emf** [comment]
For what it's worth, the copy that I have for this does not include /data/etc/cpd and /data/etc/vm; both of which are quite large and contain daily ISO images and VM images of what I think is sensor operating system code.   I did not mirror that stuff, and it brought the size of the dataset down to 19GB.
