### ISSUE TITLE
NOAA ESRL GMD Trace Gases

### ISSUE THREAD

**Issue by donbright** [climate-mirror/datasets#303]
* *Agency*:  National Oceanic & Atmospheric Administration (NOAA)
* *Agency Division*: Oceanic and Atmospheric Research (OAR)
* *Agency Subdivision*: Earth System Research Laboratory (ESRL)
* *Agency Sub-Subdivision*: Global Monitoring Division (GMD)
* *Bulk Download Link*: ftp://aftp.cmdl.noaa.gov/data/trace_gases/
* *Size Estimate*: 2.7G

* *Data Type*: Data on gases including cfc113, ch4, ch4c13, ch4h2, co, co2, co2c13, co2c14, co2o18, h2, and voc (see ftp directory list)

* *Related Issues*: This issue is a split of issue #275

**Comment by emf** [comment]
2.6GB
magnet:?xt=urn:btih:28a6b5409e6493d1be8efed09e581d46f9c2c500&dn=trace%5Fgases&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80&tr=udp%3A%2F%2Fopen.demonii.com%3A1337&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969
