### ISSUE TITLE
NOAA ESRL GMD Halocarbons and other Atmospheric Trace Species

### ISSUE THREAD

**Issue by donbright** [climate-mirror/datasets#304]
* *Agency*:  National Oceanic & Atmospheric Administration (NOAA)
* *Agency Division*: Oceanic and Atmospheric Research (OAR)
* *Agency Subdivision*: Earth System Research Laboratory (ESRL)
* *Agency Sub-Subdivision*: Global Monitoring Division (GMD)
* *Bulk Download Link*: ftp://ftp.cmdl.noaa.gov/hats/
* *Size Estimate*: 1.3G
* *Data Type*: ```"The general mission of the Halocarbons and other Atmospheric Trace Species group is to quantify the distributions and magnitudes of sources and sinks for atmospheric nitrous oxide (N2O) and halogen containing compounds."``` - [GMD HATS website](https://www.esrl.noaa.gov/gmd/hats/)
* *Related Issues*: This issue is a split of issue #275

**Comment by donbright** [comment]
mirror: offline, contact me if data is needed
hashdeep: offline, contact me if data is needed

verified hashdeep against @emf 's torrent mirror in #275 

---------
redownloaded 2017 2 19 due to hard drive failure

**Comment by ymarcus93** [comment]
**ftp.cmdl.noaa.gov_hats.tar.gz**

**Description**: ftp://ftp.cmdl.noaa.gov/hats - Distributions and magnitudes of sources and sinks for atmospheric nitrous oxide (N2O) and halogen containing compounds.
**Size**: 684 MB

**Magnet**: magnet:?xt=urn:btih:1e909cdd869e7e397bb187f4c5401e814e570cdf&dn=ftp.cmdl.noaa.gov%5Fhats.tar.gz&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80&tr=udp%3A%2F%2Fopen.demonii.com%3A1337&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969
**SHA256 Hash**: 0b805878abb3b7d116de007bc5f0c7571b5c6823a85c58f495aa75c91ca42ffb

I have created more torrents for climate data on my website: https://yuvalmarcus.io/climate/
