### ISSUE TITLE
NOAA ESRL GMD Global Greenhouse Gas Reference Network

### ISSUE THREAD

**Issue by donbright** [climate-mirror/datasets#305]
* *Agency*:  National Oceanic & Atmospheric Administration (NOAA)
* *Agency Division*: Oceanic and Atmospheric Research (OAR)
* *Agency Subdivision*: Earth System Research Laboratory (ESRL)
* *Agency Sub-Subdivision*: Global Monitoring Division (GMD)
* *Alternate name*: Carbon Cycle Greenhouse Gas group
* *Bulk Download Link*: ftp://ftp.cmdl.noaa.gov/data/ccgg
* *Size Estimate*: 106G
* *Data Type*: ```"The Global Greenhouse Gas Reference Network measures the atmospheric distribution and trends of the three main long-term drivers of climate change, carbon dioxide (CO2), methane (CH4), and nitrous oxide (N2O), as well as carbon monoxide (CO) which is an important indicator of air pollution"``` - [GMD CCGG website](https://www.esrl.noaa.gov/gmd/ccgg/)

* *Related Issues*: This issue is a split of issue #275

**Comment by williethesmith** [comment]
starting JSON for ODIAC FFCO2 measurement data 2013-2016 found here: ftp://ftp.cmdl.noaa.gov/data/ccgg/ODIAC/2015a/distrib/

**Comment by emf** [comment]
magnet:?xt=urn:btih:5ad2f0e028dd5d7bf544fe61297af083742c0ad3&dn=ccgg&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80&tr=udp%3A%2F%2Fopen.demonii.com%3A1337&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969
