### ISSUE TITLE
NOAA ESRL GMD Ozone and Water Vapor Group

### ISSUE THREAD

**Issue by donbright** [climate-mirror/datasets#306]
* *Agency*:  National Oceanic & Atmospheric Administration (NOAA)
* *Agency Division*: Oceanic and Atmospheric Research (OAR)
* *Agency Subdivision*: Earth System Research Laboratory (ESRL)
* *Agency Sub-Subdivision*: Global Monitoring Division (GMD)
* *Bulk Download Link*: ftp://aftp.cmdl.noaa.gov/data/ozwv/
* *Size Estimate*: 19G
* *Data Type*: ```"The Ozone and Water Vapor Group conducts research on the nature and causes of the depletion of the stratospheric ozone layer and the role of stratospheric and tropospheric ozone and water vapor in forcing climate change and in modifying the chemical cleansing capacity of the atmosphere"``` - [GMD Ozone & WV website](https://www.esrl.noaa.gov/gmd/ozwv//)

* *Related Issues*: This issue is a split of issue #275

**Comment by emf** [comment]
I have finished /data/ozwv. 20GB.

magnet:?xt=urn:btih:b4d47f02e908aaec2b892498a0381251a3c3fa6c&dn=ozwv&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80&tr=udp%3A%2F%2Fopen.demonii.com%3A1337&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969

**Comment by markuslaker** [comment]
Thanks for the magnet link.  I've queued it for downloading next time it becomes available, just for a redundant backup.

If you send a pull request for https://github.com/daknob/climate.daknob.net then you can get your torrent added to the bottom of the Climate Mirror Web page at https://climatemirror.org/.
