### ISSUE TITLE
NOAA ESRL GMD Station Meteorology

### ISSUE THREAD

**Issue by donbright** [climate-mirror/datasets#307]
* *Agency*:  National Oceanic & Atmospheric Administration (NOAA)
* *Agency Division*: Oceanic and Atmospheric Research (OAR)
* *Agency Subdivision*: Earth System Research Laboratory (ESRL)
* *Agency Sub-Subdivision*: Global Monitoring Division (GMD)

* *Bulk Download Link*: ftp://aftp.cmdl.noaa.gov/data/meteorology/
* *Size Estimate*: 4.4G
* *Data Type*: ```"The ESRL GMD Meteorology program measures ambient and dewpoint temperatures, relative humidity, precipitation (in inches), and wind speed and direction. . . . In order to monitor the trends in meteorological parameters, and to assist in the interpretation of other parameters such as aerosols."``` - [GMD Station Meteorology website](https://www.esrl.noaa.gov/gmd/obop/mlo/programs/esrl/met/met.html)

* *Related Issues*: This issue is a split of issue #275

**Comment by emf** [comment]
/data/meteorology is done. 4.7GB

magnet:?xt=urn:btih:7273355c230f08478459335ad549656a060c1def&dn=meteorology&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80&tr=udp%3A%2F%2Fopen.demonii.com%3A1337&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969

**Comment by markuslaker** [comment]
Thanks for the magnet link.  I'm leeching a copy from you now, just to provide a redundant backup.

If you send a pull request for <https://github.com/daknob/climate.daknob.net> then you can get your torrent added to the bottom of the Climate Mirror Web page at <https://climatemirror.org/>.  I did for a couple of mine, and they merged the PR within two minutes flat.  That said, no one's actually taken copies of the data I'm seeding, so I can't guarantee anyone will be battering down your door.

**Comment by blitzdesigner** [comment]
im grabbing this torrent too...

**Comment by gabefair** [comment]
I'm downloading a copy of the original dataset for cross-verification

**Comment by gabefair** [comment]
Here is a copy: https://www.dropbox.com/sh/pt5dk44x0q16rqn/AAB1vW5jtI5KlR5LqNWYtGqWa?dl=0 
Total size: 1.58 GB
Size on NTFS with disk compression: 465 MB
