### ISSUE TITLE
NOAA ESRL GMD CarbonTracker CO2 (Carbon Dioxide)

### ISSUE THREAD

**Issue by donbright** [climate-mirror/datasets#309]
* *Agency*:  National Oceanic & Atmospheric Administration (NOAA)
* *Agency Division*: Oceanic and Atmospheric Research (OAR)
* *Agency Subdivision*: Earth System Research Laboratory (ESRL)
* *Agency Sub-Subdivision*: Global Monitoring Division (GMD)
* *Bulk Download Link*: ftp://aftp.cmdl.noaa.gov:/products/carbontracker/co2
* *Size Estimate*: 3.4 T
* *Data Type*: ```"CarbonTracker is a CO2 measurement and modeling system developed by NOAA to keep track of sources (emissions to the atmosphere) and sinks (removal from the atmosphere) of carbon dioxide around the world. CarbonTracker uses atmospheric CO2 observations from a host of collaborators and simulated atmospheric transport to estimate these surface fluxes of CO2."``` - [GMD Carbontracker website](https://www.esrl.noaa.gov/gmd/ccgg/carbontracker/)

* *Related Issues*: This issue is a split of issue #275

**Comment by bkirkbri** [comment]
Downloading...

**Comment by donbright** [comment]
Azimuth Project has a backup as well:

https://bitbucket.org/azimuth-backup/azimuth-inventory/issues/7/noaa-carbon-tracker-ftp-site

**Comment by JeremiahCurtis** [comment]
@donbright any idea of the size of the azimuth backup?

**Comment by donbright** [comment]
according to the link above, it is "large"

**Comment by donbright** [comment]
no longer an issue
