### ISSUE TITLE
NOAA ESRL GMD CarbonTracker Lagrange

### ISSUE THREAD

**Issue by donbright** [climate-mirror/datasets#310]
* *Agency*:  National Oceanic & Atmospheric Administration (NOAA)
* *Agency Division*: Oceanic and Atmospheric Research (OAR)
* *Agency Subdivision*: Earth System Research Laboratory (ESRL)
* *Agency Sub-Subdivision*: Global Monitoring Division (GMD)

* *Bulk Download Link*:  ftp://aftp.cmdl.noaa.gov:/products/carbontracker/lagrange
* *Size Estimate*: 1.3 T
* *Data Type*: ```"CarbonTracker-Lagrange (CT-L) is a new regional inverse modeling framework currently under development and designed for estimating North American greenhouse gas emissions and uptake fluxes. CT-L uses surface sensitivity footprints from Lagrangian Particle Dispersion Models driven by high-resolution meteorological simulations. Surface fluxes are optimized for a consistency with a variety of in situ and remote sensing observations of CO2 using Bayesian and geostatistical inverse modeling techniques."``` - [GMD CT L website](https://www.esrl.noaa.gov/gmd/ccgg/carbontracker-lagrange/)

* *Related Issues*: This issue is a split of issue #275

**Comment by donbright** [comment]
Azimuth Project has a backup as well:

https://bitbucket.org/azimuth-backup/azimuth-inventory/issues/7/noaa-carbon-tracker-ftp-site

**Comment by gabefair** [comment]
lftp aftp.cmdl.noaa.gov:/products/carbontracker/lagrange> dir
drwxr-xr-x    7 300      300          1024 Jul 30  2015 footprints
drwxr-xr-x    2 300      201          4096 Apr 25  2016 obspack
drwxr-xr-x    2 300      201          1024 Nov 16 18:30 src

**Comment by donbright** [comment]
crisis has passed.
