### ISSUE TITLE
NOAA ESRL GMD Radiation

### ISSUE THREAD

**Issue by donbright** [climate-mirror/datasets#311]
* *Agency*:  National Oceanic & Atmospheric Administration (NOAA)
* *Agency Division*: Oceanic and Atmospheric Research (OAR)
* *Agency Subdivision*: Earth System Research Laboratory (ESRL)
* *Agency Sub-Subdivision*: Global Monitoring Division (GMD)
* *Bulk Download Link*:  ftp://aftp.cmdl.noaa.gov/data/radiation/
* *Size Estimate*: 196G
* *Data Type*: ```"G-Rad is involved in observational and theoretical research of the Earth's surface and atmospheric radiation budgets. The group specializes in the investigation of climatically significant variations in long-term radiation and meteorological measurements made at diverse globally-remote sites and continental US sites (SURFRAD)."``` - [GMD Radiation website](https://www.esrl.noaa.gov/gmd/grad/)

* *Related Issues*: This issue is a split of issue #275

**Comment by BauerPiepenbrink** [comment]
Downloading to offline-mirror for now

**Comment by maryannet** [comment]
This should be checked often. New data is being added daily

**Comment by emf** [comment]
/data/radiation 8.8GB

magnet:?xt=urn:btih:408dd0761724eb7ebb69de4b4204d31cbd87659e&dn=radiation&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80&tr=udp%3A%2F%2Fopen.demonii.com%3A1337&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969

**Comment by JeremiahCurtis** [comment]
running visual wget now, on ftp://aftp.cmdl.noaa.gov/data/radiation/other/

**Comment by BauerPiepenbrink** [comment]
This transfers in glacial terms of speed. got almost 4 GB in 6 days :/ . Might be due to trans-atlantic lag

Does anyone have a copy already?

**Comment by jradzuweit** [comment]
tp@sirius:~/mirrors> lftp -c "open ftp://aftp.cmdl.noaa.gov/data/radiation/ && du -h -d1"
37M     ./antuv                                                         
1.4G    ./baseline                                                               
1.2G    ./CUCF                                                                                                                             
0       ./instaar                                                         
du: Access failed: 550 Failed to change directory.                     
8.1M    ./NCDC                                                                 
48G     ./neubrew                                                                                                                    
5.3G    ./other                                                                                                     
145M    ./shiprad                                                          
141G    ./surfrad                                                                                                     
0       ./uid_shadow_drive                                                      
197G    .

Creating mirror at ftp://176.9.40.3/mirror_b, as soon as it is finished I will post an update here.

**Comment by jradzuweit** [comment]
Server seems to be reducing transmission speed

**Comment by donbright** [comment]
crisis has passed.
