### ISSUE TITLE
NOAA Datasets

### ISSUE THREAD

**Issue by Pythonmaster1508** [climate-mirror/datasets#324]
* *Agency*: NOAA
* *Agency Division*: Unknown
* *Data Type*: Dataset
* *Data Format*: Mostly HTML
* *FTP/HTTP URL*: https://data.noaa.gov/dataset?q=Climate+Change&sort=score+desc%2C+name+asc&ext_location=&ext_bbox=&ext_prev_extent=-139.21874999999997%2C8.754794702435618%2C-61.87499999999999%2C61.77312286453146&page=1

I think these might be helpful

**Comment by bkirkbri** [comment]
This search results in 5,621 datasets. More specificity is needed. There is likely overlap with many existing issues. Please refine if possible and remove duplicates. Thank you.

**Comment by Pythonmaster1508** [comment]
Please remove this issue while I figure out what does not overlap. I will repost once I figure the overlaps out

**Comment by bkirkbri** [comment]
Ok, will do.
