### ISSUE TITLE
ASDC DAAC Subset: ARCTAS/

### ISSUE THREAD

**Issue by gabefair** [climate-mirror/datasets#342]
### New Dataset

This data set is a part of a giant data set of Atmospheric Data Research Center Langley (ASDC DAAC) #337.
We needed to break that one up into parts. 

* *Agency*: NASA
* *Project Page*: https://www.nasa.gov/mission_pages/arctas/
* *Data Size*:
* *About the data*: Arctic Research of the Composition of the Troposphere from Aircraft and Satellites
* *FTP/HTTP URL*: ftp://l5eil01.larc.nasa.gov/ARCTAS/
Recommended command: `wget -N -m ftp://l5eil01.larc.nasa.gov/ARCTAS/*`

Once you are done: 
- Please post the sha256 hash results of the files. 
Recommended command:  `hashdeep -erl > l5eil01_larc_nasa_gov_ARCTAS_hash-audit.txt`
- Please compute the sizes using `du -b --max-depth=1 --human-readable` or `ls -l`
- And if your copy is online, a link to the mirror.

**Comment by jradzuweit** [comment]
this conatins only Symlinks which points  to empty directories

**Comment by gabefair** [comment]
Confirmed. Closing
