### ISSUE TITLE
Jason SAT data

### ISSUE THREAD

**Issue by nickrsan** [climate-mirror/datasets#51]
Name: Jason SAT data
Organization: 
Description URL: 
Download URL: http://sealevel.jpl.nasa.gov/missions/jason3/
File Types: 
Size: 
Status:

**Comment by donbright** [comment]
probable duplicate of #246

**Comment by bkirkbri** [comment]
Requires registration for access. Appears to be a multi-national project and should be at lower threat.

**Comment by bkirkbri** [comment]
Data may be available at #246. Closing as a duplicate.
