### ISSUE TITLE
Dataset at http://ameriflux.lbl.gov/

### ISSUE THREAD

**Issue by nickrsan** [climate-mirror/datasets#88]
Name: 
Organization: DOE
Description URL: http://ameriflux.lbl.gov/
Download URL: ftp://cdiac.ornl.gov/pub/ameriflux/data/
File Types: csv, cdf, tar.gz, txt
Size: 55 GB

**Comment by johncronan** [comment]
I downloaded as much as I could, but it was only 1.1 GB. That's the BADM files from the URLs in the attached file.

Oh, I just noticed the listed download URL. Should I add the files from the cdiac.ornl.gov FTP site?
[manifest.txt](https://github.com/climate-mirror/datasets/files/718171/manifest.txt)

**Comment by bkirkbri** [comment]
> Should I add the files from the cdiac.ornl.gov FTP site?

If you can, go for it.

**Comment by as-com** [comment]
Mirrored on my server: https://mirrors.asun.co/climate-mirror/cdiac.ornl.gov/pub/ameriflux/data/

**Comment by ewooonk** [comment]
I transferred most files of this subset to an offline mirror. I failed to transfer 15 files.

**Comment by as-com** [comment]
I also had trouble transferring some files: https://mirrors.asun.co/climate-mirror/cdiac.ornl.gov/pub/ameriflux/data/lftp-errors.txt

**Comment by zeno0771** [comment]
I will try this one as well.

**Comment by mxplusb** [comment]
closing this issue as it has one mirror.
